{{- range .Values.backupTargets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .credentialSecret }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .credentialSecret }}
  dataFrom:
    - extract:
        key: {{ .vaultPath }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
