namespace: longhorn-system
tailscale:
  hostname: storage
  tag: tag:k8s
backupTargets:
  - name: b2
    url: s3://guarnz-backup-longhorn@us-east-005/
    credentialSecret: longhorn-credentials
    vaultPath: secret/longhorn
    pollInterval: 5m0s
    cron: 0 2 * * *
    retain: 30
