apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.21.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/gitops/config/cert-manager/values.yaml
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      path: gitops/config/cert-manager/resources
      helm:
        releaseName: cert-manager-resources
        valueFiles:
          - $values/gitops/global-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
