apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.22.0
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/gitops/config/external-dns/values.yaml
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      path: gitops/config/external-dns/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
