apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.6.2
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/gitops/config/prometheus/values.yaml
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      path: gitops/config/prometheus/resources
      helm:
        releaseName: prometheus-resources
        valueFiles:
          - $values/gitops/global-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
