apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.102.3
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/gitops/config/tailscale/values.yaml
    - repoURL: https://github.com/guarnz/oke-homelab
      targetRevision: HEAD
      path: gitops/config/tailscale/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
